
volumes:
  pg_data:

services:
  postgresql:
    image: postgres:16.0-bookworm
    ports:
      - 54321:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data
